import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header/Header";
import HeaderTop from "./components/headertop/HeaderTop";
import { getUser } from "./auth/action";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  console.log(params);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <>
          <HeaderTop />
          <Header />
          <div>{children}</div>
        </>
      </body>
    </html>
  );
}
